"""Load and chunk policy documents for RAG indexing (implementation layer).

Reads PDFs from `data/policies/` (generated by `create_policy_pdfs.py`).
Not exposed to MCP directly — called by vector_store.index_documents() and
wrapped for agents via tools/document_tools.py.
"""

from __future__ import annotations

from pathlib import Path

import fitz
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter

from src.config import get_settings


def process_pdf(file_path: str) -> list[Document]:
    """Extract text from a PDF and split it into chunked documents."""
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"PDF not found: {file_path}")
    if path.suffix.lower() != ".pdf":
        raise ValueError(f"Expected a PDF file: {file_path}")

    text_parts: list[str] = []
    with fitz.open(path) as pdf:
        for page in pdf:
            page_text = page.get_text("text").strip()
            if page_text:
                text_parts.append(page_text)

    full_text = "\n\n".join(text_parts).strip()
    if not full_text:
        raise ValueError(f"No text could be extracted from PDF: {file_path}")

    base_metadata = {
        "source": str(path.resolve()),
        "filename": path.name,
    }
    document = Document(page_content=full_text, metadata=base_metadata)

    settings = get_settings()
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=settings.rag_chunk_size,
        chunk_overlap=settings.rag_chunk_overlap,
    )
    chunks = splitter.split_documents([document])
    for index, chunk in enumerate(chunks):
        chunk.metadata["chunk"] = index
    return chunks


def load_documents(policies_dir: Path) -> list[Document]:
    """Load and chunk all PDF files from the configured policies directory."""
    policies_dir.mkdir(parents=True, exist_ok=True)
    chunks: list[Document] = []
    for pdf_path in sorted(policies_dir.glob("*.pdf")):
        chunks.extend(process_pdf(str(pdf_path)))
    return chunks
